thread_num: 1

llm:
  model: "gemma4:e4b"
  api_base: "http://localhost:11434/v1"
  api_key: "ollama"

subscriptions:
  - name: "arxiv.cs.AI"
    # url: "https://rss.arxiv.org/rss/cs.AI"
    url: "http://export.arxiv.org/api/query?search_query=cat:cs.AI&max_results=10"
    max_results: 3
    interval: 30

senders:
  - name: "save_to_file"
    path: "output"
  - name: "server_chan"
